os: linux
language: shell

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
- docker

env:
  global:
  - IMAGE=gcr.io/dd-decaf-cfbf6/metabolic-ninja
  - BRANCH=${TRAVIS_BRANCH}
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_TIMESTAMP=$(date --utc --iso-8601=seconds)
  - BUILD_DATE=$(date --utc --iso-8601=date)
  - BUILD_TAG=${BRANCH}_${BUILD_DATE}_${SHORT_COMMIT}

before_install:
- ./scripts/install_gcloud.sh
- ./scripts/install_kubectl.sh
- make setup

install:
- make build-travis
- make build
- make start

script:
- make style
- make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
- docker-compose exec -e ENVIRONMENT=testing web pytest --cov=metabolic_ninja --cov-report=term --cov-report=xml
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make push; fi

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "btIzNJtN54ZVq36MQTbh8DlziDngFcUag3YfddOqy1t0Jb1Lq1uT1/ecvn9iddqVM2wzgFAdHobkE0UJaYS3q4Kyg0Yd9m9iLrIRpBnXuHScCxUUMxGvr6RCM1xaT1JgXiPejWcdBEjkXUZwwhtM2BXUCfDeIkqXbtbCp1NyLUSCCoIo4CQXRdF+SVU8z7P/BOzQGspI3UTQFdBKyatu3ipZ9sZpvG9TirhNA1jz9fJmrPFF4enGApUmPEfyT0a2ZN6aFEatewFO7dvxcZwnvpvwCuyxTupZoeNWC2nv2TZpz7Mhk0olhf89S/xpbboIYVwp7QbeWw3wFfMpepmQb60+r9SA2SJ43TLaNkDQGU25TjIaERedPYCAtOPfwG4Jmyo3+r/j2d1kklgfZEB2Qzb73YiMkDHf0nG9AijXH0+e0iuP1A+NbThZkPWcNfbRwk9ziZjahWnS3EI2iXSAXZhr0OPARnbQTiz6G4oH8Pa96bRSf9o4KNE7FLp04JVyQPBbM4Ar9SKVjli9NguoUJTyfHFw4safmVZZ3aVPLCwdAR/Nbj3RjRN0ZZQ/Zu4u0bgk6UQVuA4CglaRa20T8pkbG0Eh5pS0qRgcv3EwfZgceS8Obr7SK+evDIxly1UPbYAOhpYm1n4dUKatF+ygeWHJZAEmYqA7qQusQblUIlQ="
    on_success: change
    on_failure: change
    on_pull_requests: false
